package:
  name: ant
  version: 1.10.14
  epoch: 1
  description: A Java build tool
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - openjdk-17-default-jvm
      - openjdk-17-jre

environment:
  contents:
    packages:
      - bash
      - busybox
      - ca-certificates-bundle
      - openjdk-17

pipeline:
  - uses: fetch
    with:
      uri: https://www.apache.org/dist/ant/source/apache-ant-${{package.version}}-src.tar.bz2
      expected-sha256: c451b8abca000892ef82f9e23ab26b02369973f5ca76fdf2b8d8fa258debffef

  - runs: |
      export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
      sh build.sh install-lite -Dant.install=${{targets.destdir}}/usr/share/java/ant

      rm ${{targets.destdir}}/usr/share/java/ant/bin/*.bat
      rm ${{targets.destdir}}/usr/share/java/ant/bin/*.cmd

      mkdir -p "${{targets.destdir}}"/usr/bin

      ln -sf /usr/share/java/ant/bin/ant "${{targets.destdir}}"/usr/bin/ant

update:
  enabled: true
  release-monitor:
    identifier: 50

test:
  environment:
    contents:
      packages:
        - wolfi-base
  pipeline:
    - runs: |
        ant -version
