package:
  name: chromium
  version: 122.0.6250.1
  epoch: 0
  description: Chromium browser
  copyright:
    - license: 
  dependencies:
    runtime:
      - fontconfig
      - font-opensans
      - libnss

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - bash
      - git
      - build-base
      - python3
      - rust
      - alsa-lib-dev
      - bash
      - bison
      - brotli-dev
      - busybox
      - bzip2-dev
      - cairo-dev
      - cups-dev
      - curl-dev
      - dav1d-dev
      - elfutils
      - elfutils-dev
      - eudev-dev
      - ffmpeg-dev
      - findutils
      - flac-dev
      - flex
      - freetype-dev
      - gn
      - gperf
      - gzip
      - harfbuzz-dev
      - hwdata-dev
      - krb5-dev
      - lcms2-dev
      - libbsd-dev
      - libcap-dev
      - libevent-dev
      - libffi-dev
      - libgcrypt-dev
      - libjpeg-turbo-dev
      - libsecret-dev
      - libusb-dev
      - libva-dev
      - libwebp-dev
      - libxcomposite-dev
      - libxcursor-dev
      - libxinerama-dev
      - libxml2-dev
      - libxrandr-dev
      - libxslt-dev
      - linux-headers
      - mesa-dev
      - opus-dev
      - pciutils-dev
      - perl
      - pulseaudio-dev
      - py3-httplib2
      - py3-setuptools
      - python3
      - rust
      - samurai
      - speex-dev
      - sqlite-dev
      - wget
      - xcb-proto
      - zlib-dev
      - zstd-dev
      - glib-dev
      - dbus-glib-dev
      - libnss-dev
      - libxdamage
      - libxtst
      - mesa-gbm
      - libxkbcommon
      - pango
      - curl

pipeline:
  - runs: |
      git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
      export PATH="$PWD/depot_tools:$PATH"
      mkdir chromium && cd chromium
      cat <<EOF > .gclient
      solutions = [
        {
          "name": "src",
          "url": "https://chromium.googlesource.com/chromium/src.git",
          "managed": False,
          "custom_deps": {},
          "custom_vars": {},
        },
      ]
      EOF

      cat .gclient
      git clone https://chromium.googlesource.com/chromium/src.git --branch=${{package.version}} --depth=1
      cd src
      gclient sync --no-history
      gn gen out/Default --args="is_debug=false"

      autoninja -C out/Default chrome chromedriver chrome_sandbox

      cd out/Default
      mkdir -p ${{targets.destdir}}/usr/bin ${{targets.destdir}}/usr/lib/${{package.name}}
      mv *.so* ${{targets.destdir}}/usr/lib/${{package.name}}
      
      mv chrome ${{targets.destdir}}/usr/lib/${{package.name}}
      mv chrome_sandbox ${{targets.destdir}}/usr/lib/${{package.name}}
      mv chromedriver ${{targets.destdir}}/usr/lib/${{package.name}}

      # resources
      mv snapshot_blob.bin ${{targets.destdir}}/usr/lib/${{package.name}}
      mv v8_context_snapshot.bin ${{targets.destdir}}/usr/lib/${{package.name}}
      mv icudtl.dat ${{targets.destdir}}/usr/lib/${{package.name}}

      mv xdg-mime ${{targets.destdir}}/usr/lib/${{package.name}}
      mv xdg-settings ${{targets.destdir}}/usr/lib/${{package.name}}

      mv vk_swiftshader_icd.json ${{targets.destdir}}/usr/lib/${{package.name}}

      mv *.pak ${{targets.destdir}}/usr/lib/${{package.name}}
      mv locales ${{targets.destdir}}/usr/lib/${{package.name}}

      # links
      ln -sf /usr/lib/${{package.name}}/chrome ${{targets.destdir}}/usr/bin/chromium-browser
      ln -sf chromium-browser ${{targets.destdir}}/usr/bin/chromium

      mkdir -p ${{targets.destdir}}/etc/chromium

  - uses: strip

subpackages:
  - name: ${{package.name}}-qt
    options:
      no-depends: true
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib/${{package.name}}
          mv ${{targets.destdir}}/usr/lib/${{package.name}}/*qt* ${{targets.subpkgdir}}/usr/lib/${{package.name}}
  - name: ${{package.name}}-lang
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib/${{package.name}}
          mv ${{targets.destdir}}/usr/lib/${{package.name}}/locales ${{targets.subpkgdir}}/usr/lib/${{package.name}}