package:
  name: chromium
  version: 122.0.6250.1
  epoch: 1
  description: "Open souce version of Google's chrome web browser"
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - alsa-lib-dev
      - bash
      - bison
      - brotli-dev
      - build-base
      - busybox
      - bzip2-dev
      - ca-certificates-bundle
      - cairo-dev
      - cups-dev
      - curl
      - curl-dev
      - dav1d-dev
      - dbus-glib-dev
      - elfutils
      - elfutils-dev
      - eudev-dev
      - ffmpeg-dev
      - findutils
      - flac-dev
      - flex
      - freetype-dev
      - git
      - glib-dev
      - gn
      - gperf
      - gzip
      - harfbuzz-dev
      - hwdata-dev
      - krb5-dev
      - lcms2-dev
      - libbsd-dev
      - libcap-dev
      - libevent-dev
      - libffi-dev
      - libgcrypt-dev
      - libjpeg-turbo-dev
      - libnss-dev
      - libsecret-dev
      - libusb-dev
      - libva-dev
      - libwebp-dev
      - libxcomposite-dev
      - libxcursor-dev
      - libxdamage
      - libxinerama-dev
      - libxkbcommon
      - libxml2-dev
      - libxrandr-dev
      - libxslt-dev
      - libxtst
      - linux-headers
      - mesa-dev
      - mesa-gbm
      - opus-dev
      - pango
      - pciutils-dev
      - perl
      - pulseaudio-dev
      - py3-httplib2
      - py3-setuptools
      - python3
      - rust
      - samurai
      - speex-dev
      - sqlite-dev
      - wget
      - xcb-proto
      - zlib-dev
      - zstd-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://chromium.googlesource.com/chromium/src.git
      tag: ${{package.version}}
      depth: 1
      expected-commit: 553d92272085528d3d2c898c9263714e8ad3345b

  - runs: |
      # Mostly following: https://chromium.googlesource.com/chromium/src/+/main/docs/linux/build_instructions.md
      # Initial git clone takes ~15m
      # Fetch tools -- this is pretty quick, requires 1G of disk
      cd ..
      git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
      export PATH="$PWD/depot_tools:$PATH"
      cd -
      cat <<EOF > .gclient
      # Setup a .gclient config (handled by fetch in upstream instructions)
      solutions = [
        { "name"        : "src",
          "url"         : "https://chromium.googlesource.com/chromium/src.git",
          "managed": False,
          "custom_deps": {},
          "custom_vars": {},
        },
      ]
      EOF
      # Fetch source -- this takes about 15 minutes, requires 6G of disk
      gclient sync --no-history
      # Generate config -- this takes about 30 minutes
      gn gen out/Default --args="is_debug=false"
      # Building -- this will take a long time (~3 hours on a 32xCPU, 128GB system)
      autoninja -C out/Default chrome chromedriver chrome_sandbox
      # Install the goods
      cd out/Default
      mkdir -p ${{targets.destdir}}/usr/bin ${{targets.destdir}}/usr/lib/${{package.name}}
      mv *.so* ${{targets.destdir}}/usr/lib/${{package.name}}
      mv chrome ${{targets.destdir}}/usr/lib/${{package.name}}
      mv chrome_sandbox ${{targets.destdir}}/usr/lib/${{package.name}}
      mv chromewebdriver ${{targets.destdir}}/usr/lib/${{package.name}}
      # resources
      mv snapshot_blob.bin ${{targets.destdir}}/usr/lib/${{package.name}}
      mv v8_context_snapshot.bin ${{targets.destdir}}/usr/lib/${{package.name}}
      # links
      ln -sf /usr/lib/${{package.name}}/chrome ${{targets.destdir}}/usr/bin/chromium-browser
      ln -sf chromium-browser ${{targets.destdir}}/usr/bin/chromium

  - uses: strip
