package:
  name: clang-17
  version: 17.0.0_rc1
  epoch: 0
  description: "C language family frontend for LLVM"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - libLLVM-17

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - cmake
      - samurai
      - binutils-dev
      - libffi-dev
      - zlib-dev
      - libxml2-dev
      - pkgconf
      - python3
      - help2man
      - llvm17
      - llvm17-dev
      - libLLVM-17

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.0-rc1/clang-17.0.0rc1.src.tar.xz
      expected-sha256: 4069d0f8d5eb8715762391b1a771b2b6d2d9b5e00775a18de6a8914ae579e25b

  - uses: fetch
    with:
      uri: https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.0-rc1/clang-tools-extra-17.0.0rc1.src.tar.xz
      expected-sha256: 39fb223330c718eee7b0b3fdefee358a1461a38e6ffc09b043904a4606eeccc1
      strip-components: 0

  - uses: fetch
    with:
      uri: https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.0-rc1/cmake-17.0.0rc1.src.tar.xz
      expected-sha256: 52ba10684ce50c639517fea73082ede73af7b76baf375d384cfa9ff52dcd3128
      strip-components: 0

  - runs: |
      mv cmake-*.src ../cmake

  - runs: |
      mv clang-tools-extra-*.src tools/extra

  - runs: |
      python_version=$(python3 -V | sed 's/.*\([0-9]\{1,\}\.[0-9]\{1,\}\)\..*/\1/')

      cmake -B build -G Ninja -Wno-dev \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_MODULE_PATH="../cmake/Modules" \
        -DCLANG_BUILT_STANDALONE=TRUE \
        -DCLANG_CONFIG_FILE_SYSTEM_DIR=/etc/clang17 \
        -DLLVM_CONFIG=/usr/lib/llvm17/bin/llvm-config \
        -DCLANG_ENABLE_ARCMT=ON \
        -DCLANG_ENABLE_STATIC_ANALYZER=ON \
        -DCLANG_INCLUDE_TESTS=OFF \
        -DCLANG_LINK_CLANG_DYLIB=ON \
        -DCLANG_PLUGIN_SUPPORT=ON \
        -DCLANG_PYTHON_BINDINGS_VERSIONS="$python_version" \
        -DCLANG_VENDOR=Wolfi \
        -DENABLE_LINKER_BUILD_ID=ON \
        -DLIBCLANG_BUILD_STATIC=ON \
        -DLLVM_INCLUDE_DIRS=/usr/lib/llvm17/include \
        -DLLVM_INCLUDE_TESTS=OFF

  - runs: |
      cmake --build build --target clang-tblgen

  - runs: |
      cmake --build build

  - runs: |
      help2man --no-info \
        --source "Wolfi" \
        --name "Wolfi Clang ${{package.version}}-r${{package.epoch}}" \
        --version-string "${{package.version}}-r${{package.epoch}}" \
        --help-option "--help-hidden" \
        ./build/bin/clang > clang.1

  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install build

      install -Dm644 build/lib/libclang.a -t "${{targets.destdir}}"/usr/lib/

  - runs: |
      rm "${{targets.destdir}}"/usr/share/clang/clang-format-bbedit.applescript \
         "${{targets.destdir}}"/usr/share/clang/clang-doc-default-stylesheet.css \
         "${{targets.destdir}}"/usr/share/clang/index.js

      install -Dm644 clang.1 -t "${{targets.destdir}}"/usr/share/man/man1/

      mkdir -p "${{targets.destdir}}"/usr/share/bash-completion/completions
      mv "${{targets.destdir}}"/usr//share/clang/bash-autocomplete.sh \
         "${{targets.destdir}}"/usr/share/bash-completion/completions/clang

      mkdir -p "${{targets.destdir}}"/usr/share/emacs/site-lisp
      mv "${{targets.destdir}}"/usr/share/clang/clang-*.el \
         "${{targets.destdir}}"/usr/share/emacs/site-lisp

  - uses: strip

subpackages:
  - name: "clang-17-dev"
    description: "headers for clang-17"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libLLVM-17
        - libclang-cpp-17

  - name: "libclang-cpp-17"
    description: "Clang 17 runtime library"
    pipeline:
      - runs: |
          sonamefull="libclang-cpp.so.17git"

          mkdir -p "${{targets.subpkgdir}}"/usr/lib/
          mv "${{targets.destdir}}"/usr/lib/$sonamefull "${{targets.subpkgdir}}"/usr/lib/
    dependencies:
      runtime:
        - libLLVM-17

  - name: "clang-17-analyzer"
    description: "Clang 17 analyzer"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/scan* "${{targets.subpkgdir}}"/usr/bin/
          mv "${{targets.destdir}}"/usr/bin/analyze-build* "${{targets.subpkgdir}}"/usr/bin/
          mv "${{targets.destdir}}"/usr/bin/intercept-build* "${{targets.subpkgdir}}"/usr/bin/

          mkdir -p "${{targets.subpkgdir}}"/usr/libexec
          mv "${{targets.destdir}}"/usr/libexec/*-analyzer* "${{targets.subpkgdir}}"/usr/libexec/
          mv "${{targets.destdir}}"/usr/libexec/analyze-* "${{targets.subpkgdir}}"/usr/libexec/
          mv "${{targets.destdir}}"/usr/libexec/intercept-* "${{targets.subpkgdir}}"/usr/libexec/

          mkdir -p "${{targets.subpkgdir}}"/usr/share
          mv "${{targets.destdir}}"/usr/share/scan-* "${{targets.subpkgdir}}"/usr/share/

          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libear* "${{targets.subpkgdir}}"/usr/lib/
    dependencies:
      runtime:
        - perl
        - python3

  - name: "clang-17-extras"
    description: "Clang 17 extras"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/clang-apply-replacements* "${{targets.subpkgdir}}"/usr/bin/
          mv "${{targets.destdir}}"/usr/bin/clang-change-namespace* "${{targets.subpkgdir}}"/usr/bin/
          mv "${{targets.destdir}}"/usr/bin/clang-check* "${{targets.subpkgdir}}"/usr/bin/
          mv "${{targets.destdir}}"/usr/bin/clang-doc* "${{targets.subpkgdir}}"/usr/bin/
          mv "${{targets.destdir}}"/usr/bin/clang-extdef-mapping* "${{targets.subpkgdir}}"/usr/bin/
          mv "${{targets.destdir}}"/usr/bin/clang-format* "${{targets.subpkgdir}}"/usr/bin/
          mv "${{targets.destdir}}"/usr/bin/clang-include-fixer* "${{targets.subpkgdir}}"/usr/bin/
          mv "${{targets.destdir}}"/usr/bin/clang-move* "${{targets.subpkgdir}}"/usr/bin/
          mv "${{targets.destdir}}"/usr/bin/clang-offload-bundler* "${{targets.subpkgdir}}"/usr/bin/
          mv "${{targets.destdir}}"/usr/bin/clang-offload-packager* "${{targets.subpkgdir}}"/usr/bin/
          mv "${{targets.destdir}}"/usr/bin/clang-query* "${{targets.subpkgdir}}"/usr/bin/
          mv "${{targets.destdir}}"/usr/bin/clang-refactor* "${{targets.subpkgdir}}"/usr/bin/
          mv "${{targets.destdir}}"/usr/bin/clang-rename* "${{targets.subpkgdir}}"/usr/bin/
          mv "${{targets.destdir}}"/usr/bin/clang-reorder-fields* "${{targets.subpkgdir}}"/usr/bin/
          mv "${{targets.destdir}}"/usr/bin/clang-repl* "${{targets.subpkgdir}}"/usr/bin/
          mv "${{targets.destdir}}"/usr/bin/clang-scan-deps* "${{targets.subpkgdir}}"/usr/bin/
          mv "${{targets.destdir}}"/usr/bin/clang-tidy* "${{targets.subpkgdir}}"/usr/bin/
          mv "${{targets.destdir}}"/usr/bin/clangd* "${{targets.subpkgdir}}"/usr/bin/
          mv "${{targets.destdir}}"/usr/bin/c-index-test* "${{targets.subpkgdir}}"/usr/bin/
          mv "${{targets.destdir}}"/usr/bin/diagtool* "${{targets.subpkgdir}}"/usr/bin/
          mv "${{targets.destdir}}"/usr/bin/find-all-symbols* "${{targets.subpkgdir}}"/usr/bin/
          mv "${{targets.destdir}}"/usr/bin/git-clang-format* "${{targets.subpkgdir}}"/usr/bin/
          mv "${{targets.destdir}}"/usr/bin/hmaptool* "${{targets.subpkgdir}}"/usr/bin/
          mv "${{targets.destdir}}"/usr/bin/modularize* "${{targets.subpkgdir}}"/usr/bin/
          mv "${{targets.destdir}}"/usr/bin/pp-trace* "${{targets.subpkgdir}}"/usr/bin/
          mv "${{targets.destdir}}"/usr/bin/run-clang-tidy* "${{targets.subpkgdir}}"/usr/bin/

          mkdir -p "${{targets.subpkgdir}}"/usr/share/clang
          mv "${{targets.destdir}}"/usr/share/clang/clang-include-fixer* "${{targets.subpkgdir}}"/usr/share/clang/
          mv "${{targets.destdir}}"/usr/share/clang/clang-format*.py "${{targets.subpkgdir}}"/usr/share/clang/
          mv "${{targets.destdir}}"/usr/share/clang/*clang-tidy* "${{targets.subpkgdir}}"/usr/share/clang/
          mv "${{targets.destdir}}"/usr/share/clang/run-find-all-symbols.py "${{targets.subpkgdir}}"/usr/share/clang/

          mv "${{targets.destdir}}"/usr/share/emacs "${{targets.subpkgdir}}"/usr/share/

  - name: "py3-clang-17"
    description: "Clang 17 Python bindings"
    pipeline:
      - runs: |
          sitedir=$(python3 -c "import site; print(site.getsitepackages()[0])")

          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/python* "${{targets.subpkgdir}}"/usr/lib/

          mkdir -p "${{targets.subpkgdir}}"/usr/share/clang
          mv "${{targets.destdir}}"/usr/share/clang/clang-rename.py "${{targets.subpkgdir}}"/usr/share/clang/

          mv "${{targets.destdir}}"/usr/lib/libscanbuild "${{targets.subpkgdir}}"/"$sitedir"
    dependencies:
      runtime:
        - libLLVM-17
        - libclang-cpp-17

update:
  enabled: true
  github:
    identifier: llvm/llvm-project
    strip-prefix: llvmorg-
    tag-filter: llvmorg-17
    use-tag: true
