package:
  name: curl
  version: 7.86.0
  epoch: 1
  description: "URL retrieval utility and library"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: MIT

secfixes:
  7.86-r1:
    - CVE-2022-42916

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - nghttp2-dev
      - openssl-dev
      - zlib-dev
      - brotli-dev

pipeline:
  - uses: fetch
    with:
      uri: https://curl.se/download/curl-${{package.version}}.tar.xz
      expected-sha256: 3dfdd39ba95e18847965cd3051ea6d22586609d9011d91df7bc5521288987a82
  - uses: autoconf/configure
    with:
      opts: |
        --enable-ipv6 \
        --enable-unix-sockets \
        --with-openssl \
        --with-nghttp2 \
        --with-pic \
        --disable-ldap \
        --without-libssh2    
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip

subpackages:
  - name: "curl-dev"
    description: "headers for libcurl"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libcurl4

  - name: "curl-doc"
    description: "documentation for curl"
    pipeline:
      - uses: split/manpages

  - name: "libcurl4"
    description: "curl library"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libcurl.so.* "${{targets.subpkgdir}}"/usr/lib/
