package:
  name: deno
  version: 1.31.2
  epoch: 0
  description: "A modern runtime for JavaScript and TypeScript."
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - rust
      - libLLVM-15
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - glibc-dev
      - posix-libc-utils
      - bash

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/denoland/deno/releases/download/v${{package.version}}/deno_src.tar.gz
      expected-sha256: 09f84d841e83cd3e22ccfe320097857da8aa908030409d48034377b81850de76
  - name: Configure and build
    runs: |
      cargo build --release -vv
      mkdir -p ${{targets.destdir}}/usr/bin/
      mv target/release/deno ${{targets.destdir}}/usr/bin/
  - uses: strip

advisories:
  CVE-2023-22499:
    - timestamp: 2023-02-11T12:51:24.232894-05:00
      status: fixed
      fixed-version: 1.30.0-r0

secfixes:
  1.30.0-r0:
    - CVE-2023-22499
