package:
  name: erlang
  version: 25.3.2
  epoch: 1
  description: General-purpose programming language and runtime environment
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - perl-dev
      - openssl-dev
      - ncurses-dev
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: aed4e4726cdc587ab820c8379d63e511e46a1b1cc0c59d6a720b51ae625b2510
      uri: https://github.com/erlang/otp/releases/download/OTP-${{package.version}}/otp_src_${{package.version}}.tar.gz

  - runs: |
      export CPPFLAGS="-D_BSD_SOURCE $CPPFLAGS"

      # There's an internal compiler error triggered on arm that breaks jit compilation.
      jit="--enable-jit"
      if "${{build.arch}}" == "aarch64"; then
        jit="--disable-jit"
      fi

      ./otp_build autoconf
      ./configure \
        --prefix=/usr \
        --sysconfdir=/etc \
        --mandir=/usr/share/man \
        --infodir=/usr/share/info \
        --host="$CHOST" \
        --build="$CBUILD" \
        --enable-threads \
        --enable-shared-zlib \
        --enable-ssl=dynamic-ssl-lib \
        $jit

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "erlang-dev"
    description: "headers for erlang"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - erlang

update:
  enabled: true
  github:
    identifier: erlang/otp
    strip-prefix: OTP-
    use-tag: true
    tag-filter: OTP-
