package:
  name: flux
  version: 0.41.1
  epoch: 1
  description: Open and extensible continuous delivery solution for Kubernetes. Powered by GitOps Toolkit.
  copyright:
    - license: Apache-2.0
environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - build-base
      - bash
      - curl
      - go
      - kustomize
      - git
pipeline:
  - uses: fetch
    with:
      uri: https://github.com/fluxcd/flux2/archive/v${{package.version}}/v${{package.version}}.tar.gz
      expected-sha256: 1e875dba2c25911d0ca98781f54023a9c9020a9ec94c0f290d50adf19972c2fc
  - runs: |
      mkdir -p "${{targets.destdir}}"/usr/bin
      VERSION=${{package.version}} make build
      install -Dm755 bin/flux ${{targets.destdir}}/usr/bin/flux
  - runs: |
      ${{targets.destdir}}/usr/bin/flux version --client| grep "flux: v${{package.version}}"
  - uses: strip
