package:
  name: fzf
  version: 0.54.1
  epoch: 0
  description: A command-line fuzzy finder
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/junegunn/fzf
      tag: v${{package.version}}
      expected-commit: 50fa90dfb8eab7f03a7602ea9c098b01ff7236e8

  - uses: go/build
    with:
      packages: .
      output: fzf
      ldflags: -s -w  -X main.version=v${{ package.version }} -X main.revision=$(git rev-parse --short HEAD)

  - uses: strip

update:
  enabled: true
  github:
    identifier: junegunn/fzf
    strip-prefix: v
    use-tag: true
