package:
  name: icu
  version: 71.1
  epoch: 0
  description: "International Components for Unicode library"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: MIT
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage3
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage3/wolfi-signing.rsa.pub
    packages:
      - wolfi-baselayout
      - busybox
      - build-base
      - python3

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/unicode-org/icu/releases/download/release-${{package.version}}icu4c-${{package.version}}-src.tgz
      expected-sha256: 26e6e4d60ad59b3fff9948eb36743f0c874e124e410ef5bab930d0f546bc580d
  - runs: |
      ./configure \
        --host=$(uname -m)-pc-linux-gnu \
        --target=$(uname -m)-pc-linux-gnu \
        --prefix=/usr \
        --enable-shared
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip

subpackages:
  - name: "isl-dev"
    description: "integer set library development headers"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - isl
