package:
  name: libreoffice
  version: 24.2.0.2
  epoch: 0
  description:
  copyright:
    - license: GPL-3.0
  options:
    no-provides: true

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - bison
      - build-base
      - busybox
      - cairo-dev
      - coreutils
      - cups-dev
      - curl
      - dbus-dev
      - diffutils
      - expat-dev
      - flex
      - fontconfig-dev
      - freetype-dev
      - fribidi-dev
      - glib-dev
      - gnutar
      - gperf
      - gst-plugins-base-dev
      - gstreamer-dev
      - gtk-3-dev
      - harfbuzz-dev
      - krb5-dev
      - libassuan-dev
      - libatk-1.0
      - libatk-bridge-2.0
      - libice-dev
      - libnspr-dev
      - libnss-dev
      - libsm-dev
      - libtool
      - libx11-dev
      - libxcomposite-dev
      - libxcursor-dev
      - libxdamage-dev
      - libxft-dev
      - libxml2-dev
      - libxrandr-dev
      - libxrender
      - libxslt-dev
      - libxt-dev
      - libxtst-dev
      - m4
      - mesa-dev
      - mesa-egl
      - mesa-gl
      - nasm
      - orc-dev
      - pango-dev
      - patch
      - perl
      - pkgconf
      - pkgconf-dev
      - python-3.11
      - python-3.11-dev
      - zip

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/LibreOffice/core

  - runs: |
      ./autogen.sh --with-java=no --prefix=/usr
      sed -i 's/bootstrap: check-if-root/bootstrap: /g' Makefile.in

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    pipeline:
      - uses: split/dev

update:
  enabled: true
  github:
    identifier: LibreOffice/core
    use-tag: true
    strip-prefix: libreoffice-
