package:
  name: llvm17
  version: 17.0.0_rc1
  # This is an RC. When changing to a release version, you'll need to change:
  # * the URI in the fetch statements
  # * the soname in the subpackage
  epoch: 0
  description: "low-level virtual machine - core frameworks"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - cmake
      - samurai
      - binutils-dev
      - libffi-dev
      - zlib-dev
      - libxml2-dev
      - pkgconf
      - python3
      - git

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.0-rc1/llvm-17.0.0rc1.src.tar.xz
      expected-sha256: bed01361c60a17d3bc37da4879711134e5680e273db31e27c4f2a0da4ac0e35d
      extract: false

  - uses: fetch
    with:
      uri: https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.0-rc1/cmake-17.0.0rc1.src.tar.xz
      expected-sha256: 52ba10684ce50c639517fea73082ede73af7b76baf375d384cfa9ff52dcd3128
      extract: false

  - runs: |
      # This build is a bit unusual and requires two separate checkouts next to each other
      # We need to set extract: false above and do the unpacking manually here.
      # We then set working-directory below in the pipeline to the llvm checkout.
      tar -xf llvm-*.src.tar.xz
      tar -xf cmake-*.src.tar.xz
      mv llvm-*.src llvm
      mv cmake-*.src cmake

  - working-directory: /home/build/llvm
    pipeline:
      - runs: |
          find /home/build/
          ffi_include_dir="$(pkg-config --cflags-only-I libffi | sed 's|^-I||g')"

          cmake -B build -G Ninja -Wno-dev \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=/usr/lib/llvm17 \
            -DCMAKE_MODULE_PATH=/home/build/cmake/Modules \
            -DFFI_INCLUDE_DIR="${ffi_include_dir}" \
            -DLLVM_BINUTILS_INCDIR=/usr/include \
            -DLLVM_BUILD_DOCS=OFF \
            -DLLVM_BUILD_EXAMPLES=OFF \
            -DLLVM_BUILD_EXTERNAL_COMPILER_RT=ON \
            -DLLVM_BUILD_LLVM_DYLIB=ON \
            -DLLVM_BUILD_TESTS=OFF \
            -DLLVM_INCLUDE_TESTS=OFF \
            -DLLVM_DEFAULT_TARGET_TRIPLE="$(uname -m)-unknown-linux-gnu" \
            -DLLVM_ENABLE_ASSERTIONS=OFF \
            -DLLVM_ENABLE_FFI=ON \
            -DLLVM_ENABLE_LIBCXX=OFF \
            -DLLVM_ENABLE_PIC=ON \
            -DLLVM_ENABLE_RTTI=ON \
            -DLLVM_ENABLE_SPHINX=OFF \
            -DLLVM_ENABLE_TERMINFO=ON \
            -DLLVM_ENABLE_ZLIB=ON \
            -DLLVM_INSTALL_UTILS=ON \
            -DLLVM_HOST_TRIPLE="$(uname -m)-unknown-linux-gnu" \
            -DLLVM_INCLUDE_EXAMPLES=OFF \
            -DLLVM_LINK_LLVM_DYLIB=ON \
            -DLLVM_APPEND_VC_REV=OFF \
            -DLLVM_INCLUDE_BENCHMARKS=OFF
      - runs: |
          cmake --build build --target llvm-tblgen
      - runs: |
          cmake --build build
      - runs: |
          DESTDIR="${{targets.destdir}}" cmake --install build
      - runs: |
          mkdir -p "${{targets.destdir}}"/usr/bin

          for path in "${{targets.destdir}}"/usr/lib/llvm17/bin/*; do
            name=${path##*/}
            ln -s ../lib/llvm17/bin/$name "${{targets.destdir}}"/usr/bin/$name
          done
      - runs: |
          cd "${{targets.destdir}}"/usr/lib/llvm17

          mkdir -p "${{targets.destdir}}"/usr/lib/
          for path in "${{targets.destdir}}"/usr/lib/llvm17/lib/*.a; do
            name=${path##*/}
            ln -s ../lib/llvm17/lib/$name "${{targets.destdir}}"/usr/lib/$name
          done

          mkdir -p "${{targets.destdir}}"/usr/lib/
          for path in "${{targets.destdir}}"/usr/lib/llvm17/lib/*.so*; do
            name=${path##*/}
            ln -s ../lib/llvm17/lib/$name "${{targets.destdir}}"/usr/lib/$name
          done
      - working-directory: ${{targets.destdir}}/usr/lib/llvm17
        runs: |
          mkdir -p "${{targets.destdir}}"/usr/lib/cmake
          mv lib/cmake/llvm "${{targets.destdir}}"/usr/lib/cmake/llvm17
          ln -s llvm17 "${{targets.destdir}}"/usr/lib/cmake/llvm
      - uses: strip

subpackages:
  - name: "libLLVM-17"
    description: "LLVM 17 runtime library"
    pipeline:
      - runs: |
          soname="libLLVM-17git.so"
          sonamefull="libLLVM-${{package.version}}.so"

          mkdir -p "${{targets.subpkgdir}}"/usr/lib/llvm17/lib/
          mv "${{targets.destdir}}"/usr/lib/llvm17/lib/$soname "${{targets.subpkgdir}}"/usr/lib/
          ln -s $soname "${{targets.subpkgdir}}"/usr/lib/$sonamefull
          ln -s $soname "${{targets.subpkgdir}}"/usr/lib/libLLVM.so

          ln -s ../../$soname "${{targets.subpkgdir}}"/usr/lib/llvm17/lib/$soname
          ln -s ../../$soname "${{targets.subpkgdir}}"/usr/lib/llvm17/lib/$sonamefull

          rm -f "${{targets.destdir}}"/usr/lib/llvm17/lib/$soname
          rm -f "${{targets.destdir}}"/usr/lib/llvm17/lib/$sonamefull

          rm -f "${{targets.destdir}}"/usr/lib/$soname
          rm -f "${{targets.destdir}}"/usr/lib/$sonamefull

  - name: "llvm17-dev"
    description: "headers for llvm17"
    pipeline:
      - uses: split/dev
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib/llvm17/bin
          mv "${{targets.destdir}}"/usr/lib/llvm17/bin/llvm-config "${{targets.subpkgdir}}"/usr/lib/llvm17/bin/

          soname="libLLVM-17.so"
          sonamefull="libLLVM-${{package.version}}.so"

          rm -f "${{targets.subpkgdir}}"/usr/lib/llvm17/lib/$soname
          rm -f "${{targets.subpkgdir}}"/usr/lib/llvm17/lib/$sonamefull

          rm -f "${{targets.subpkgdir}}"/usr/lib/libLLVM.so
          rm -f "${{targets.subpkgdir}}"/usr/lib/$soname
          rm -f "${{targets.subpkgdir}}"/usr/lib/$sonamefull
    dependencies:
      runtime:
        - libLLVM-17

update:
  enabled: true
  github:
    identifier: llvm/llvm-project
    strip-prefix: llvmorg-
    tag-filter: llvmorg-17
    use-tag: true
