package:
  name: node
  version: v16.17.0
  epoch: 0
  description: "nodejs"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: |
        Copyright 1992, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2005,
        2006, 2007, 2008, 2010, 2011, 2013, 2014, 2022 Free Software Foundation,
        Inc.
      license: GPL-3.0-or-later
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage3
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage3/wolfi-signing.rsa.pub
    packages:
      - wolfi-baselayout
      - busybox
      - build-base
      - scanelf
      - ca-certificates-bundle
      - brotli-dev
      - c-ares-dev
      - icu-dev
      - linux-headers
      - nghttp2-dev
      - openssl-dev
      - python3
      - py3-jinja2
      - samurai
      - zlib-dev


pipeline:
  - uses: fetch
    with:
      uri: https://nodejs.org/dist/${{package.version}}/node-${{package.version}}.tar.gz
      expected-sha256: 2a2e6262739741f98ab81648a50891861dbf66f12413b93f1a97b4c71570611e
  - name: Configure
    runs: |
        python3 configure.py --prefix=/usr \
          --shared-brotli \
          --shared-zlib \
          --shared-openssl \
          --shared-cares \
          --shared-nghttp2 \
          --ninja \
          --openssl-use-def-ca-store \
          --with-icu-default-data-dir=$(icu-config --icudatadir) \
          --with-intl=system-icu \
          --without-corepack \
          --without-npm
  - runs: |
      make BUILDTYPE=Release
  - uses: autoconf/make-install
  - uses: strip