package:
  name: oauth2-proxy
  version: 7.4.0
  epoch: 0
  description: Configure external DNS servers (AWS Route53, Google CloudDNS and others) for Kubernetes Ingresses and Services.
  target-architecture:
    - all
  copyright:
    - license: Apache-2.0
      paths:
        - "*"
environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/oauth2-proxy/oauth2-proxy
      tag: v${{package.version}}
      expected-commit: aafa96655048bc1ed26487e92410f5fe64968fa2
  - runs: |
      make build
      touch jwt_signing_key.pem
      mkdir -p ${{targets.destdir}}/usr/bin
      mv oauth2-proxy ${{targets.destdir}}/usr/bin/
update:
  enabled: true
  github:
    identifier: oauth2-proxy/oauth2-proxy
    strip-prefix: v
