package:
  name: pcre2
  version: "10.43"
  epoch: 0
  description: "perl-compatible regular expression library"
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - automake
      - autoconf
      - build-base
      - busybox
      - ca-certificates-bundle
      - libedit-dev
      - wolfi-base
      - zlib-dev
      - libtool

pipeline:
  - uses: fetch
    with:
      uri: "https://github.com/PCRE2Project/pcre2/archive/refs/tags/pcre2-${{package.version}}.tar.gz"
      expected-sha256: f0048e26b02bdfaf43b8cec75030a9c2fe28552bf5caa693d3ccbf4d886fa930
  
  - runs: autoreconf -fiv

  - uses: autoconf/configure
    with:
      opts: --enable-jit --enable-pcre2-16 --enable-pcre2-32 --enable-pcre2grep-libz --enable-pcre2test-libedit

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "pcre2-doc"
    description: "pcre2 documentation"
    pipeline:
      - uses: split/manpages
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share
          mv "${{targets.destdir}}"/usr/share/doc "${{targets.subpkgdir}}"/usr/share/

  - name: "pcre2-dev"
    description: "pcre2 development headers"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libpcre2-8-0
        - libpcre2-16-0
        - libpcre2-32-0
        - libpcre2-posix-3
        - libedit-dev
        - zlib-dev

  - name: "libpcre2-8-0"
    description: "pcre2 runtime library 8-bit"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libpcre2-8* "${{targets.subpkgdir}}"/usr/lib/

  - name: "libpcre2-16-0"
    description: "pcre2 runtime library 16-bit"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libpcre2-16* "${{targets.subpkgdir}}"/usr/lib/

  - name: "libpcre2-32-0"
    description: "pcre2 runtime library 32-bit"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libpcre2-32* "${{targets.subpkgdir}}"/usr/lib/

  - name: "libpcre2-posix-3"
    description: "pcre2 runtime library (posix)"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libpcre2-posix* "${{targets.subpkgdir}}"/usr/lib/

update:
  enabled: true
  release-monitor:
    identifier: 5832
