package:
  name: ruby-3.2
  version: 3.2.1
  epoch: 0
  description: "the Ruby programming language"
  copyright:
    - license: PSF-2.0
  dependencies:
    runtime:

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - bzip2-dev
      - expat-dev
      - gdbm-dev
      - libffi-dev
      - yaml-dev
      - linux-headers
      - mpdecimal-dev
      - ncurses-dev
      - openssl-dev
      - readline-dev
      - sqlite-dev
      - xz-dev
      - zlib-dev
      - oniguruma-dev
      - rust
      - libLLVM-15

pipeline:
  - uses: fetch
    with:
      uri: https://cache.ruby-lang.org/pub/ruby/3.2/ruby-${{package.version}}.tar.gz
      expected-sha256: 13d67901660ee3217dbd9dd56059346bd4212ce64a69c306ef52df64935f8dbd
  - name: Configure
    runs: |
      ./configure \
         --host=${{host.triplet.gnu}} \
         --build=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr \
         --enable-ipv6 \
         --enable-loadable-sqlite-extensions \
         --enable-optimizations \
         --enable-shared \
         --without-lto \
         --with-computed-gotos \
         --with-dbmliborder=gdbm:ndbm \
         --with-system-expat \
         --with-system-ffi \
         --with-system-libmpdec \
         --without-ensurepip \
         --enable-yjit
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip

subpackages:
  - name: "ruby-3.2-doc"
    description: "ruby documentation"
    pipeline:
      - uses: split/manpages
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share
          mv "${{targets.destdir}}"/usr/share/doc "${{targets.subpkgdir}}"/usr/share/
          mv "${{targets.destdir}}"/usr/share/ri "${{targets.subpkgdir}}"/usr/share/

  - name: "ruby-3.2-dev"
    description: "ruby development headers"
    pipeline:
      - uses: split/dev
