package:
  name: scala3
  version: 3.2.2
  epoch: 0  
  description: The scala compiler
  copyright:
      license: Apache-2.0
  dependencies:
    runtime:
      - openjdk-17-jre
      - bash
environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
pipeline:
  - uses: fetch
    with:
      expected-sha256: b7c5edef42e8cde3e80d71372077a358e4d608461c399cad4432b3fd0c609998
      uri: https://github.com/lampepfl/dotty/releases/download/${{package.version}}/scala3-${{package.version}}.tar.gz
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/share/java/scala
      mkdir -p ${{targets.destdir}}/usr/share/java/scala/bin
      mkdir -p ${{targets.destdir}}/usr/share/java/scala/lib
      mkdir -p ${{targets.destdir}}/usr/bin/

      ln -sf /usr/share/java/scala/bin/scaladoc ${{targets.destdir}}/usr/bin/
      ln -sf /usr/share/java/scala/bin/scalac ${{targets.destdir}}/usr/bin/
      ln -sf /usr/share/java/scala/bin/scalap ${{targets.destdir}}/usr/bin/
      ln -sf /usr/share/java/scala/bin/scala ${{targets.destdir}}/usr/bin/

      mv lib/* ${{targets.destdir}}/usr/share/java/scala/lib
      mv bin/* ${{targets.destdir}}/usr/share/java/scala/bin
