package:
  name: skopeo
  version: 1.15.2
  epoch: 0
  description: Work with remote images registries - retrieving information, images, signing content
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 0002d9ca10ba2038b2d6171e4878b49340c5d954
      repository: https://github.com/containers/skopeo
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/docker/docker@v25.0.5 golang.org/x/net@v0.23.0 github.com/hashicorp/go-retryablehttp@v0.7.7

  - runs: |
      CGO_ENABLED=0 go build -mod=vendor \
        -tags "exclude_graphdriver_devicemapper exclude_graphdriver_btrfs containers_image_openpgp" \
        -trimpath -ldflags "-s -w -extldflags -static -buildid=" \
        -o "${{targets.destdir}}/usr/bin/skopeo" ./cmd/skopeo

  - uses: strip

update:
  enabled: true
  github:
    identifier: containers/skopeo
    strip-prefix: v
    use-tag: true
