package:
  name: terraform
  version: 1.3.9
  epoch: 2
  copyright:
    - license: MPL-2.0
environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - go
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hashicorp/terraform
      tag: v${{package.version}}
      expected-commit: 30dcdb076504d4549f12b64a9ff658f0dea8d75f
      destination: terraform
  - runs: |
      cd terraform

      # Mitigate GHSA-jpxj-2jvg-6jv9 (CVE-2023-0475)
      go get github.com/hashicorp/go-getter@v1.7.0

      # Mitigate GHSA-vvpx-j8f3-3w6h (CVE-2022-41723)
      go get golang.org/x/net@v0.7.0

      go generate ./...
      CGO_ENABLED=0 go build -v
  - runs: |
      install -m755 -D ./terraform/terraform "${{targets.destdir}}/usr/bin/terraform"
  - uses: strip
