package:
  name: visualization-server
  version: 2.0.5
  epoch: 0
  description: Machine Learning Pipelines for Kubeflow
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - python-3.10

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3.10-pip
      - python-3.10
      - python-3.10-dev
      #- py3.10-tensorflow-data-validation
      - py3.10-tensorflow-core

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubeflow/pipelines
      tag: ${{package.version}}
      expected-commit: c5658f09ec38e82730a8eca0a1aabf0876087eec

  - uses: patch
    with:
      patches: bump.patch

  - runs: |
      ln -sf /usr/bin/python3.10 /usr/bin/python3
      mkdir -p ${{targets.destdir}}/usr/share/app
      cp -r backend/src/apiserver/visualization/* ${{targets.destdir}}/usr/share/app/
      cd ${{targets.destdir}}/usr/share/app/

      # sed -i 's/tensorflow==/#tensorflow==/g' requirements.txt
      
      pip install --root=${{targets.destdir}} --prefix=/usr -r requirements.txt
      find ${{targets.destdir}} -name "*.pyc" -exec rm -rf '{}' +

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubeflow/pipelines
    use-tag: true
