package:
  name: xz
  version: 5.4.6
  epoch: 0
  description: "Library and CLI tools for XZ and LZMA compressed files"
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - gettext
      - gettext-dev
      - libtool
      - m4
      - wolfi-baselayout

pipeline:
  - uses: fetch # use fetch instead of git-checkout else there is a circular dependency with git
    with:
      uri: https://github.com/tukaani-project/xz/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: 60831005fddb270824fa9f7cdd28a59da8757fe95466ed5b10bcfe23379f17d9

  - name: Configure
    runs: |
      autoreconf -fiv
      ./configure \
         --host=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr \
         --datadir=/usr/share

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "xz-dev"
    description: "xz headers"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - xz

  - name: "xz-doc"
    description: "xz documentation"
    pipeline:
      - uses: split/manpages

update:
  enabled: false
  github:
    identifier: tukaani-project/xz
    strip-prefix: v
