package:
  name: xz
  version: 5.6.1
  epoch: 0
  description: "Library and CLI tools for XZ and LZMA compressed files"
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - wolfi-baselayout

pipeline:
  - runs: |
      ls
      tar --strip-components=1 -xf sha256:2398f4a8e53345325f44bdd9f0cc7401bd9025d736c6d43b372f4dea77bf75b8

  - uses: autoconf/configure
    with:
      opts: |
        --host=${{host.triplet.gnu}} \
        --target=${{host.triplet.gnu}} \
        --prefix=/usr \
        --datadir=/usr/share

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "xz-dev"
    description: "xz headers"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - xz

  - name: "xz-doc"
    description: "xz documentation"
    pipeline:
      - uses: split/manpages

update:
  enabled: false
  github:
    identifier: tukaani-project/xz
    strip-prefix: v
